### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by csabyka** [aluminiumgeek/goodbye-mihome#3]
Dear Mikhail 

Please help me (im very weak in python)
python mihome.py

> Traceback (most recent call last):
>   File "mihome.py", line 16, in <module>
>     from plugins import sensor_ht, gateway, yeelight
>   File "/usr/src/goodbye-mihome/plugins/gateway.py", line 1, in <module>
>     from plugins.gateway_led import STORE_KEY as LED_STORE_KEY
>   File "/usr/src/goodbye-mihome/plugins/gateway_led.py", line 6, in <module>
>     from mihome import get_key, send_command
>   File "/usr/src/goodbye-mihome/mihome.py", line 16, in <module>
>     from plugins import sensor_ht, gateway, yeelight
>   File "/usr/src/goodbye-mihome/plugins/yeelight.py", line 85
>     def set_scene(state_type, *args, device_id=None):
>                                              ^
> SyntaxError: invalid syntax

I cant understand whats wrong with it. 
First, i extend the mihome.py and w.py with one option (the host)
`conn = psycopg2.connect("dbname={} user={} password={} host={}".format(config.DBNAME, config.DBUSER, config.DBPASS, config.HOST))`
i updated the config.py with the host parameter, changed the sensors id but still wrong.

Csaba

**Comment by aluminiumgeek** [comment]
Hi there!

Ensure you have Python >=3.4. This module uses syntax that is not supported by Python 2.x

**Comment by csabyka** [comment]
Hey, 

Thanks for your help, but still error :(

> python3.4 mihome.py
> Traceback (most recent call last):
>   File "mihome.py", line 16, in <module>
>     from plugins import sensor_ht, gateway, yeelight
>   File "/usr/src/goodbye-mihome/plugins/gateway.py", line 1, in <module>
>     from plugins.gateway_led import STORE_KEY as LED_STORE_KEY
>   File "/usr/src/goodbye-mihome/plugins/gateway_led.py", line 6, in <module>
>     from mihome import get_key, send_command
>   File "/usr/src/goodbye-mihome/mihome.py", line 16, in <module>
>     from plugins import sensor_ht, gateway, yeelight
> ImportError: cannot import name 'gateway'

csaba

**Comment by aluminiumgeek** [comment]
@csabyka I just pushed a fix for this. Do a `git pull` and try again, please.
Feel free to write here if you have any other problems.

**Comment by csabyka** [comment]
Hey

First error (no another process in port 8888)
> Exception in thread Thread-3:
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.4/threading.py", line 868, in run
>     self._target(*self._args, **self._kwargs)
>   File "mihome.py", line 39, in receiver
>     sock.bind(("0.0.0.0", port))
> OSError: [Errno 98] Address already in use

when i try in browser:


> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1467, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "/usr/src/goodbye-mihome/web/w.py", line 66, in get
>     brightness, color, status = gateway_led.get_status()
>   File "/usr/src/goodbye-mihome/plugins/gateway_led.py", line 30, in get_status
>     return value[:2].decode(), value[2:].decode(), not store.get(STORE_KEY + 'off')
> AttributeError: 'str' object has no attribute 'decode'

Can u add the "host" parameter to mihome and w ? 
`conn = psycopg2.connect("dbname={} user={} password={} host={}".format(config.DBNAME, config.DBUSER, config.DBPASS, config.HOST))`

sometimes the psql cant understand. 

cs

**Comment by aluminiumgeek** [comment]
1. It's about 9898 (used for listening to gateway multicast packets) or 1982 (for yeelight) ports.
2. Thanks for report. This only happens with fresh install (when redis has no stored gateway key yet). I missed that during testing. Pushed a fix, please update.

**Comment by csabyka** [comment]
Dear Mikhail
It's works now :) 
The last question. The bulbs/switches is sensors too ? Need to put there the id's or have different format? 

cs

**Comment by aluminiumgeek** [comment]
@csabyka Yeelight bulb will be autodiscovered if it's powered on, no need to add it by hands. As for switches - I don't have one and didn't make a plugin for it yet, so can't tell exactly.

**Comment by csabyka** [comment]
well, u need a donate button and i can buy one to repay your kindness.

**Comment by aluminiumgeek** [comment]
@csabyka haha, yeah. I added one to README. You could close this issue if program seems good.
