### ISSUE TITLE
web interface is empty

### ISSUE THREAD

**Issue by Quentinvarquet** [aluminiumgeek/goodbye-mihome#5]
Hello,

I am using your work (thank you !) on a raspberry pi. The configuration is fine but the web interface is empty : 

![image](https://user-images.githubusercontent.com/7962157/32985898-8892baae-ccc5-11e7-97c8-fe876f4e18bc.png)

My gateway is changing the light every 10 seconds (from the configuration file)

Do you have any idea why I can't see my temperature devices ? (i have 6)

Here is the output on my raspberry ; 

![image](https://user-images.githubusercontent.com/7962157/32985910-cedc1992-ccc5-11e7-9759-ac64e5b3fa63.png)

Thank you ! :)

**Comment by Quentinvarquet** [comment]
Ok, i just had to be patient... It's working !

**Comment by aluminiumgeek** [comment]
You could push button on temperature sensor to immediately store current temperature/humidity, so you will not need to wait until device will automatically send its data.

Also put your favorite wallpapers to `web/static/img/bg/` directory to get great background.
