### ISSUE TITLE
Allow specification of Postgres host address and port

### ISSUE THREAD

**Issue by isaric** [aluminiumgeek/goodbye-mihome#9]
As an operator I want to be able to specify the Postgres host address and port. (in case it is not local)

Based on some local tinkering at least the following files need to be ammended:

- mihome.py - call to psycopg2.connect
- web/w.py - call to psycopg2.connect
- config.py.example - add host and port dummy properties

**Comment by isaric** [comment]
If approved, I am willing to code myself and open PR

**Comment by aluminiumgeek** [comment]
@isaric  Would be nice to have it

**Comment by isaric** [comment]
Can this be marked as closed? @aluminiumgeek

**Comment by aluminiumgeek** [comment]
Sure!
